version: '3'
services:
  neo4j:
    container_name: neo4j
    image: neo4j:4.3.3
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/import:/import
      - ./neo4j/logs:/logs
      - ./neo4j/plugins:/plugins
    user: "${UID}:${GID}"
volumes:
  neo4j:
