name: base
channels:
  - defaults
dependencies:
  - boltons=23.0.0=py310haa95532_0
  - brotlipy=0.7.0=py310h2bbff1b_1002
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2023.05.30=haa95532_0
  - certifi=2023.5.7=py310haa95532_0
  - cffi=1.15.1=py310h2bbff1b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - colorama=0.4.6=py310haa95532_0
  - conda=23.5.0=py310haa95532_0
  - conda-content-trust=0.1.3=py310haa95532_0
  - conda-pack=0.6.0=pyhd3eb1b0_0
  - conda-package-handling=2.0.2=py310haa95532_0
  - conda-package-streaming=0.7.0=py310haa95532_0
  - conda-token=0.4.0=pyhd3eb1b0_0
  - console_shortcut=0.1.1=4
  - cryptography=39.0.1=py310h21b164f_2
  - idna=3.4=py310haa95532_0
  - jsonpatch=1.32=pyhd3eb1b0_0
  - jsonpointer=2.1=pyhd3eb1b0_0
  - libffi=3.4.4=hd77b12b_0
  - menuinst=1.4.19=py310h59b6b97_0
  - openssl=3.0.9=h2bbff1b_0
  - packaging=23.0=py310haa95532_0
  - pip=22.3.1=py310haa95532_0
  - pluggy=1.0.0=py310haa95532_1
  - powershell_shortcut=0.0.1=3
  - pycosat=0.6.4=py310h2bbff1b_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=23.0.0=py310haa95532_0
  - pysocks=1.7.1=py310haa95532_0
  - python=3.10.12=he1021f5_0
  - requests=2.29.0=py310haa95532_0
  - ruamel.yaml=0.17.21=py310h2bbff1b_0
  - ruamel.yaml.clib=0.2.6=py310h2bbff1b_1
  - setuptools=65.6.3=py310haa95532_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.2=h2bbff1b_0
  - tk=8.6.12=h2bbff1b_0
  - toolz=0.12.0=py310haa95532_0
  - tqdm=4.65.0=py310h9909e9c_0
  - tzdata=2023c=h04d1e81_0
  - urllib3=1.26.16=py310haa95532_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.38.4=py310haa95532_0
  - win_inet_pton=1.1.0=py310haa95532_0
  - wincertstore=0.2=py310haa95532_2
  - xz=5.4.2=h8cc25b3_0
  - zlib=1.2.13=h8cc25b3_0
  - zstandard=0.19.0=py310h2bbff1b_0
prefix: C:\ProgramData\anaconda3
