server.host: "0.0.0.0"
server.port: 8084
server.verbose: True

encoder.pca_path: "..\\pca\\model.joblib"
encoder.work_embedding_path: "..\\fasttext\\wiki.en.bin"

step_sim_threshold: 0.7
var_sim_threshold: 0.8