name: test
channels:
  - pytorch
  - anaconda
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - asttokens=2.2.1=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.5=pyhd8ed1ab_0
  - blas=1.0=mkl
  - brotli=1.0.9=h8ffe710_7
  - brotli-bin=1.0.9=h8ffe710_7
  - brotlipy=0.7.0=py39h2bbff1b_1003
  - ca-certificates=2023.5.7=h56e8100_0
  - certifi=2023.5.7=pyhd8ed1ab_0
  - cffi=1.15.1=py39h2bbff1b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cloudpickle=2.2.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - cryptography=39.0.1=py39h21b164f_0
  - cuda-cccl=12.2.53=0
  - cuda-cudart=11.7.99=0
  - cuda-cudart-dev=11.7.99=0
  - cuda-cupti=11.7.101=0
  - cuda-libraries=11.7.1=0
  - cuda-libraries-dev=11.7.1=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvrtc-dev=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-runtime=11.7.1=0
  - cycler=0.11.0=pyhd8ed1ab_0
  - debugpy=1.5.1=py39hd77b12b_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - farama-notifications=0.0.4=pyhd8ed1ab_0
  - filelock=3.9.0=py39haa95532_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=ha860e81_0
  - gensim=4.3.0=py39hd77b12b_0
  - gymnasium=0.28.1=py39hbeae4fa_0
  - icc_rt=2022.1.0=h6049295_2
  - icu=68.2=h0e60522_0
  - idna=3.4=py39haa95532_0
  - importlib-metadata=6.8.0=pyha770c72_0
  - importlib_metadata=6.8.0=hd8ed1ab_0
  - intel-openmp=2023.1.0=h59b6b97_46319
  - ipykernel=6.15.0=pyh025b116_0
  - ipython=8.14.0=pyh08f2357_0
  - jax-jumpy=1.0.0=pyhd8ed1ab_0
  - jedi=0.18.2=pyhd8ed1ab_0
  - jinja2=3.1.2=py39haa95532_0
  - joblib=1.1.1=py39haa95532_0
  - jpeg=9e=h2bbff1b_0
  - jupyter_client=8.3.0=pyhd8ed1ab_0
  - jupyter_core=5.3.1=py39hcbf5309_0
  - kiwisolver=1.4.4=py39h2e07f2f_0
  - lerc=3.0=hd77b12b_0
  - libbrotlicommon=1.0.9=h8ffe710_7
  - libbrotlidec=1.0.9=h8ffe710_7
  - libbrotlienc=1.0.9=h8ffe710_7
  - libclang=11.1.0=default_h5c34c98_1
  - libcublas=11.10.3.66=0
  - libcublas-dev=11.10.3.66=0
  - libcufft=10.7.2.124=0
  - libcufft-dev=10.7.2.124=0
  - libcurand=10.3.3.53=0
  - libcurand-dev=10.3.3.53=0
  - libcusolver=11.4.0.1=0
  - libcusolver-dev=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libcusparse-dev=11.7.4.91=0
  - libdeflate=1.8=h2bbff1b_5
  - libnpp=11.7.4.75=0
  - libnpp-dev=11.7.4.75=0
  - libnvjpeg=11.8.0.2=0
  - libnvjpeg-dev=11.8.0.2=0
  - libpng=1.6.37=h2a8f88b_0
  - libsodium=1.0.18=h8d14728_1
  - libtiff=4.5.0=h6c2663c_1
  - libuv=1.44.2=h2bbff1b_0
  - libwebp=1.2.4=h2bbff1b_0
  - libwebp-base=1.2.4=h2bbff1b_0
  - lz4-c=1.9.4=h2bbff1b_0
  - markupsafe=2.1.1=py39h2bbff1b_0
  - matplotlib=3.5.3=py39hcbf5309_2
  - matplotlib-base=3.5.3=py39he03a255_2
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mkl=2023.1.0=h8bd8f75_46356
  - mkl-service=2.4.0=py39h2bbff1b_1
  - mkl_fft=1.3.6=py39hf11a4ad_1
  - mkl_random=1.2.2=py39hf11a4ad_1
  - mpmath=1.2.1=py39haa95532_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - networkx=2.8.4=py39haa95532_1
  - numpy=1.25.0=py39h055cbcc_0
  - numpy-base=1.25.0=py39h65a83cf_0
  - openssl=1.1.1u=h2bbff1b_0
  - packaging=23.1=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=9.3.0=py39hd77b12b_2
  - pip=23.1.2=py39haa95532_0
  - platformdirs=2.5.2=py39haa95532_0
  - pooch=1.7.0=pyha770c72_3
  - prompt-toolkit=3.0.39=pyha770c72_0
  - prompt_toolkit=3.0.39=hd8ed1ab_0
  - psutil=5.9.0=py39h2bbff1b_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=pyhd8ed1ab_0
  - pyopenssl=23.0.0=py39haa95532_0
  - pyparsing=3.1.0=pyhd8ed1ab_0
  - pyqt=5.12.3=py39hb0d2dfa_4
  - pysocks=1.7.1=py39haa95532_0
  - python=3.9.17=h6244533_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytorch=2.0.1=py3.9_cuda11.7_cudnn8_0
  - pytorch-cuda=11.7=h16d0643_5
  - pytorch-mutex=1.0=cuda
  - pywin32=305=py39h2bbff1b_0
  - pyyaml=6.0=py39hb82d6ee_4
  - pyzmq=25.1.0=py39hd77b12b_0
  - qt=5.12.9=h5909a2a_4
  - requests=2.29.0=py39haa95532_0
  - scikit-learn=1.2.2=py39hd77b12b_1
  - scipy=1.10.1=py39hdcfc7df_1
  - setuptools=67.8.0=py39haa95532_0
  - six=1.16.0=pyh6c4a22f_0
  - smart_open=6.3.0=pyhd8ed1ab_1
  - sqlite=3.41.2=h2bbff1b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - sympy=1.11.1=py39haa95532_0
  - tbb=2021.8.0=h59b6b97_0
  - threadpoolctl=3.2.0=pyha21a80b_0
  - tk=8.6.12=h2bbff1b_0
  - tornado=6.2=py39hb82d6ee_0
  - traitlets=5.9.0=pyhd8ed1ab_0
  - typing_extensions=4.6.3=py39haa95532_0
  - tzdata=2023c=h04d1e81_0
  - urllib3=1.26.16=py39haa95532_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - wheel=0.38.4=py39haa95532_0
  - win_inet_pton=1.1.0=py39haa95532_0
  - xz=5.2.10=h8cc25b3_1
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.4=h0e60522_1
  - zipp=3.16.2=pyhd8ed1ab_0
  - zlib=1.2.13=h8cc25b3_0
  - zstd=1.5.2=h19a0ad4_0
  - pip:
      - pyqt5-sip==4.19.18
      - pyqtchart==5.12
      - pyqtwebengine==5.12.1
      - torchaudio==2.0.2
      - torchvision==0.15.2
prefix: C:\Users\david\.conda\envs\debugpilot
